# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-16 08:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='payment_mode',
            field=models.CharField(default=b'Online', max_length=10),
        ),
        migrations.AlterField(
            model_name='profile',
            name='payment_paid',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='payment_to_be_paid',
            field=models.IntegerField(default=250),
        ),
    ]
